spring:
  datasource:
    type: com.zaxxer.hikari.util.DriverDataSource
    url: jdbc:oracle:thin:@racdesa.btl.com.pe:1521:xe
    username: PTOVENTA
    password: desarac
    driver-class-name: oracle.jdbc.driver.OracleDriver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
      pool-name: HikariPoolRAC
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
  flyway:
    schemas: ci02authentication